apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connection-pool
  namespace: pqlite-namespace
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connection-pool-binding
  namespace: pqlite-namespace
roleRef:
  apiGroup: ''
  kind: Role
  name: connection-pool
subjects:
- apiGroup: ''
  kind: ServiceAccount
  name: default
---
apiVersion: v1
data:
  JINA_LOG_LEVEL: DEBUG
  pythonunbuffered: '1'
  worker_class: uvicorn.workers.UvicornH11Worker
kind: ConfigMap
metadata:
  name: indexer-1-configmap
  namespace: pqlite-namespace
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: indexer-1
  name: indexer-1
  namespace: pqlite-namespace
spec:
  ports:
  - name: port-expose
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-in
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: indexer-1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-1
  namespace: pqlite-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: indexer-1
        jina_pod_name: indexer
        ns: pqlite-namespace
        pea_type: WORKER
        shard_id: '1'
    spec:
      containers:
      - args:
        - executor
        - --name
        - indexer-1
        - --workspace
        - /Users/fengwang/Jina/workspace/pqlite/examples/k8s_example
        - --identity
        - 2c5a73a889eb4a1cafe048f8cf4ac04f
        - --workspace-id
        - 0ece5f58518e4f18ba488d5794a6a2cd
        - --k8s-namespace
        - pqlite-namespace
        - --uses
        - config.yml
        - --port-in
        - '8081'
        - --num-part
        - '1'
        - --upload-files
        - --shard-id
        - '1'
        - --noblock-on-start
        - --shards
        - '3'
        - --uses-metas
        - '{"pea_id": 1}'
        - --native
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_POD_NAME
          value: indexer
        envFrom:
        - configMapRef:
            name: indexer-1-configmap
        image: jinahub/pn1qofsj:61d3cb5cb09768049daa3914
        imagePullPolicy: IfNotPresent
        name: executor
        ports:
        - containerPort: 8080
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8081
