apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connection-pool
  namespace: {{ template "pqlite-helm.namespace" . }}
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connection-pool-binding
  namespace: {{ template "pqlite-helm.namespace" . }}
roleRef:
  apiGroup: ''
  kind: Role
  name: connection-pool
subjects:
- apiGroup: ''
  kind: ServiceAccount
  name: default
