apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connection-pool
  namespace: pqlite-namespace
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connection-pool-binding
  namespace: pqlite-namespace
roleRef:
  apiGroup: ''
  kind: Role
  name: connection-pool
subjects:
- apiGroup: ''
  kind: ServiceAccount
  name: default
---
apiVersion: v1
data:
  JINA_LOG_LEVEL: DEBUG
  pythonunbuffered: '1'
  worker_class: uvicorn.workers.UvicornH11Worker
kind: ConfigMap
metadata:
  name: gateway-configmap
  namespace: pqlite-namespace
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: pqlite-namespace
spec:
  ports:
  - name: port-expose
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-in
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: gateway
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: pqlite-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
        jina_pod_name: gateway
        ns: pqlite-namespace
        pea_type: GATEWAY
        shard_id: ''
    spec:
      containers:
      - args:
        - gateway
        - --identity
        - f81e28ebcadd4137ac9b1abcdc3e0376
        - --workspace-id
        - 9fd4938a0f8d4a599d9ee41e7b351302
        - --k8s-namespace
        - pqlite-namespace
        - --port-in
        - '8081'
        - --expose-endpoints
        - '{}'
        - --protocol
        - HTTP
        - --port-expose
        - '8080'
        - --graph-description
        - '{"indexer": ["end-gateway"], "start-gateway": ["indexer"]}'
        - --pea-role
        - GATEWAY
        - --noblock-on-start
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_POD_NAME
          value: gateway
        envFrom:
        - configMapRef:
            name: gateway-configmap
        image: jina:k8s-py38-perf
        imagePullPolicy: IfNotPresent
        name: executor
        ports:
        - containerPort: 8080
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8080
