apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: {{ .Release.Name }}-gateway
  namespace: {{ template "pqlite-helm.namespace" . }}
spec:
  ports:
  - name: port-expose
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-in
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: gateway
  type: ClusterIP
