name: Release CD

on:
  push:
    tags:
      - "v*"  # push to version tags trigger the build

#on:
#  push:
#    branches-ignore:
#      - '**'  # temporally disable this action

jobs:
  create-release:
    needs: update-doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: |
          python scripts/get-last-release-note.py
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: 💫 Patch ${{ github.ref }}
          body_path: 'tmp.md'
          draft: false
          prerelease: false
